# Generated by Django 6.0.7 on 2026-07-10 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.')),
                ('note_type', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('MEETING', 'Meeting'), ('DEMO', 'Demo'), ('OBJECTION', 'Objection'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('note_text', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'ordering': ('-created_at',),
            },
        ),
    ]
